server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crawler?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123

http-client-pool:
  max-total: 20
  default-max-per-route: 4
  connect-timeout: 20000
  connection-request-timeout: 10000
  socket-timeout: 60000
  read-timeout: 60000